# Generated by Django 4.0.4 on 2022-04-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subtitle',
            field=models.CharField(default='Default subtitle', max_length=25),
        ),
    ]
