# Generated by Django 4.0.4 on 2022-04-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subtitle',
            field=models.CharField(default='Default subtitle text (editable)', max_length=50),
        ),
    ]
